// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ThQkoOr95OVcuO5P1nEyrzhM-K_5CVU',
    appId: '1:350594135123:android:f688a9334c1ca051e642a6',
    messagingSenderId: '350594135123',
    projectId: 'pawpaw-9d57b',
    storageBucket: 'pawpaw-9d57b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv6j5IQc-Uxk4GqgvYauy2fkfeKxX7xN0',
    appId: '1:350594135123:ios:2efc9e6dd8d7b98ae642a6',
    messagingSenderId: '350594135123',
    projectId: 'pawpaw-9d57b',
    storageBucket: 'pawpaw-9d57b.appspot.com',
    iosClientId: '350594135123-ndfc3ur3kng225qofqj810jd2bgr0siu.apps.googleusercontent.com',
    iosBundleId: 'com.pawrent.pawrent',
  );
}
